---
# tasks file for yauh.munin

- name: Monitoring via munin-node will be installed
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
     - munin-node
     - munin-plugins-extra
     - libio-all-lwp-perl

- name: Set munin-node config file
  template: src=munin-node.conf.j2 dest=/etc/munin/munin-node.conf owner=root group=root mode=0755

- name: Grab munin plugins
  action: get_url url={{ item }} dest=/usr/share/munin/plugins/ mode=0755
  with_items:
     - https://raw.github.com/munin-monitoring/contrib/master/plugins/nginx/nginx-combined
     - https://raw.github.com/munin-monitoring/contrib/master/plugins/nginx/nginx_memory

- name: Configure master
  include: master.yml
  when: "'munin-master' in group_names"

- name: Munin should be restarted
  action: service name=munin-node state=restarted

- name: nginx should be restarted
  service: name=nginx state=restarted
