- name: Monitoring via munin will be installed
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
     - munin
     - nginx
     - fcgiwrap
     - libcgi-fast-perl
     - python-passlib

- name: Copy munin-fastcgi
  template: src=munin-fastcgi.j2 dest=/etc/init.d/munin-fastcgi owner=root group=root mode=0755

- name: Set munin config file
  action: template src=munin.conf.j2 dest=/etc/munin/munin.conf owner=root group=root mode=0755
  notify: restart munin

- name: Correct hostname for munin
  shell: sed -e  "s/\[localhost.localdomain\]/[{{ansible_fqdn}}]/" /etc/munin/munin.conf

- name: Restrict access to munin web
  htpasswd: path=/etc/nginx/munin.users name={{item.name}} password={{item.password}} owner=root group=www-data mode=0640
  with_items: munin_users

- name: Configuration file for the overview site
  template: src=munin.nginx.j2 dest=/etc/nginx/sites-available/munin

- file: path=/etc/nginx/sites-enabled/default state=absent

- file: src=/etc/nginx/sites-available/munin dest=/etc/nginx/sites-enabled/munin state=link

- name: Activate plugins
  action: file src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items:
     - nginx-combined
     - nginx_memory

- name: Munin should be running
  service: name=munin state=running

- name: nginx should be running
  service: name=nginx state=running
